[Clients]
Tokens={ca277d86-6ad0-424e-909e-ec802213e584}

[Ntfy-internal]
LastMessageId=
Topics=upe2ZiMDlhMTA4

[%7Bca277d86-6ad0-424e-909e-ec802213e584%7D]
Description=Receiving notifications for new messages
Endpoint="https://unifiedpush.kde.org/upe2ZiMDlhMTA4?up=1"
RemoteId=upe2ZiMDlhMTA4
ServiceName=org.kde.neochat
VAPIDKey=
Version=2
