
$background = rgba(070b14ff)

$error = rgba(ff4e66ff)

$error_container = rgba(8c1d18ff)

$inverse_on_surface = rgba(1a1a1aff)

$inverse_primary = rgba(8800ffff)

$inverse_surface = rgba(f5f5f5ff)

$on_background = rgba(e6edf7ff)

$on_error = rgba(601410ff)

$on_error_container = rgba(f9dedcff)

$on_primary = rgba(e6edf7ff)

$on_primary_container = rgba(e6edf7ff)

$on_primary_fixed = rgba(e6edf7ff)

$on_primary_fixed_variant = rgba(e6edf7ff)

$on_secondary = rgba(e6edf7ff)

$on_secondary_container = rgba(e6edf7ff)

$on_secondary_fixed = rgba(e6edf7ff)

$on_secondary_fixed_variant = rgba(e6edf7ff)

$on_surface = rgba(e6edf7ff)

$on_surface_variant = rgba(cbd5e1ff)

$on_tertiary = rgba(e6edf7ff)

$on_tertiary_container = rgba(e6edf7ff)

$on_tertiary_fixed = rgba(e6edf7ff)

$on_tertiary_fixed_variant = rgba(e6edf7ff)

$outline = rgba(1a1a2eff)

$outline_variant = rgba(111827ff)

$primary = rgba(8800ffff)

$primary_container = rgba(6600ccff)

$primary_fixed = rgba(6600ccff)

$primary_fixed_dim = rgba(8800ffff)

$scrim = rgba(000000ff)

$secondary = rgba(bb88ffff)

$secondary_container = rgba(0f172aff)

$secondary_fixed = rgba(bb88ffff)

$secondary_fixed_dim = rgba(bb88ffff)

$shadow = rgba(000000ff)

$source_color = rgba(8800ffff)

$surface = rgba(0b0f1aff)

$surface_bright = rgba(162033ff)

$surface_container = rgba(0a1220ff)

$surface_container_high = rgba(0f172aff)

$surface_container_highest = rgba(162033ff)

$surface_container_low = rgba(0b0f1aff)

$surface_container_lowest = rgba(070b14ff)

$surface_dim = rgba(070b14ff)

$surface_tint = rgba(8800ffff)

$surface_variant = rgba(111827ff)

$tertiary = rgba(bb88ffff)

$tertiary_container = rgba(0f172aff)

$tertiary_fixed = rgba(bb88ffff)

$tertiary_fixed_dim = rgba(bb88ffff)


