
$background = rgba(1a1110ff)

$error = rgba(f2b8b5ff)

$error_container = rgba(8c1d18ff)

$inverse_on_surface = rgba(231918ff)

$inverse_primary = rgba(d32f2fff)

$inverse_surface = rgba(fff8f7ff)

$on_background = rgba(f1dedcff)

$on_error = rgba(601410ff)

$on_error_container = rgba(f9dedcff)

$on_primary = rgba(000000ff)

$on_primary_container = rgba(f1dedcff)

$on_primary_fixed = rgba(000000ff)

$on_primary_fixed_variant = rgba(000000ff)

$on_secondary = rgba(000000ff)

$on_secondary_container = rgba(f1dedcff)

$on_secondary_fixed = rgba(000000ff)

$on_secondary_fixed_variant = rgba(000000ff)

$on_surface = rgba(f1dedcff)

$on_surface_variant = rgba(d8c2beff)

$on_tertiary = rgba(000000ff)

$on_tertiary_container = rgba(f1dedcff)

$on_tertiary_fixed = rgba(000000ff)

$on_tertiary_fixed_variant = rgba(000000ff)

$outline = rgba(a08c89ff)

$outline_variant = rgba(534341ff)

$primary = rgba(f44336ff)

$primary_container = rgba(4a0e0eff)

$primary_fixed = rgba(4a0e0eff)

$primary_fixed_dim = rgba(f44336ff)

$scrim = rgba(000000ff)

$secondary = rgba(f28b82ff)

$secondary_container = rgba(322826ff)

$secondary_fixed = rgba(f28b82ff)

$secondary_fixed_dim = rgba(f28b82ff)

$shadow = rgba(000000ff)

$source_color = rgba(f44336ff)

$surface = rgba(1a1110ff)

$surface_bright = rgba(3d3231ff)

$surface_container = rgba(271d1cff)

$surface_container_high = rgba(322826ff)

$surface_container_highest = rgba(3d3231ff)

$surface_container_low = rgba(1a1110ff)

$surface_container_lowest = rgba(1a1110ff)

$surface_dim = rgba(1a1110ff)

$surface_tint = rgba(f28b82ff)

$surface_variant = rgba(534341ff)

$tertiary = rgba(f28b82ff)

$tertiary_container = rgba(322826ff)

$tertiary_fixed = rgba(f28b82ff)

$tertiary_fixed_dim = rgba(f28b82ff)


